stages:
  data_ingestion:
    cmd: py -m src.customerChurn.pipeline.stage_01_data_ingestion_pipeline
    deps:
      - src/customerChurn/pipeline/stage_01_data_ingestion_pipeline.py
      - src/customerChurn/components/data_ingestion.py
    params:
      - config/customerChurnConfig.yaml:
        - data_ingestion
  data_validation:
    cmd: py -m src.customerChurn.pipeline.stage_02_data_validation_pipeline
    deps:
      - src/customerChurn/pipeline/stage_02_data_validation_pipeline.py
      - src/customerChurn/components/data_validation.py
    params:
      - config/customerChurnConfig.yaml:
        - data_validation
      - schema/customerChurnSchema.yaml:
    outs:
      - artifacts/data_validation/status.txt
  data_transformation:
    cmd: py -m src.customerChurn.pipeline.stage_03_data_transformation_pipeline
    deps:
      - src/customerChurn/pipeline/stage_03_data_transformation_pipeline.py
      - src/customerChurn/components/data_transformation.py
    params:
      - config/customerChurnConfig.yaml:
        - data_transformation
      - schema/customerChurnSchema.yaml:
        - targer_colunm
    outs:
      - artifacts/data_transformation/preprocessor.pkl
      - artifacts/data_transformation/test.csv
      - artifacts/data_transformation/train.csv
  
  data_training:
    cmd: py -m src.customerChurn.pipeline.stage_04_data_training_pipeline
    deps: 
      - src/customerChurn/pipeline/stage_04_data_training_pipeline.py
      - src/customerChurn/components/data_trainer.py
    params:
      - config/customerChurnConfig.yaml:
        - model_trainer
      - params/customerChurnParams.yaml:
        - model_trainer
    outs:
      - artifactsmodel_trainer/bestParams.txt
      - artifacts/model_trainer/model.pkl